name: "GCR Push"
description: "Build Docker image and push it to the Google Container Registry"
inputs:
  service_account_key:
    required: true
    description: "GCP service account credentials used to log in to GCP."
  region:
    required: true
    description: "GCP region to use."
  project_id:
    required: true
    description: "GCP project id to push the image to."
  repository:
    required: true
    description: "Artifact repository name."
  image_name:
    required: true
    description: "Name of the image to push."
  image_version:
    required: false
    description: "Version to tag the image with. Defaults to latest"
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: GCP Login
      uses: "google-github-actions/auth@v3"
      with:
        credentials_json: "${{ inputs.service_account_key }}"

    - name: Google Cloud SDK setup
      uses: "google-github-actions/setup-gcloud@v3"

    - name: GCR login
      shell: bash
      run: |
        gcloud auth configure-docker -q

    - name: Extract metadata (tags, labels) for Docker 💽 
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.region }}-docker.pkg.dev/${{ inputs.project_id }}/${{ inputs.repository }}/${{ inputs.image_name }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ env.tag }}

    - name: Build and push 🐳
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
